---
swagger: "2.0"
info:
  description: "thumbnail"
  version: "1.0.0"
  title: "thumbnail"
host: "thumbnail.org"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /images:
    get:
      summary: "Get a list of images"
      description: "Get a list of images"
      x-escapin-handler: "instance.imagesGET"
      parameters: []
      responses:
        200:
          description: "A list of images"
          schema:
            $ref: "#/definitions/List"
    post:
      summary: "Upload an image and create a thumbnail"
      description: "Upload an image and create a thumbnail of it"
      x-escapin-handler: "instance.imagesPOST"
      consumes:
      - "multipart/form-data"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "name"
        in: "formData"
        description: "name of an image"
        required: true
        type: "string"
      - name: "image"
        in: "formData"
        description: "An image"
        required: true
        type: "file"
      responses:
        201:
          description: "Resource Created"
          schema:
            $ref: "#/definitions/Id"
        400:
          description: "Illegal Argument"
          schema:
            $ref: "#/definitions/ErrorMessage"
        default:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ErrorMessage"
  /images/{id}:
    parameters:
    - name: "id"
      in: "path"
      description: "id of an image"
      required: true
      type: "string"
    get:
      summary: "Download an image"
      description: "Download an image by id"
      x-escapin-handler: "instance.imagesIdGET"
      produces:
      - "application/octet-stream"
      responses:
        200:
          description: "an image"
        404:
          description: "Resource Not Found"
          schema:
            $ref: "#/definitions/ErrorMessage"
        default:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ErrorMessage"
    delete:
      summary: "Delete an image"
      description: "Delete an image by id"
      x-escapin-handler: "instance.imagesIdDELETE"
      responses:
        200:
          description: "Succeeded"
          schema:
            $ref: "#/definitions/Message"
        404:
          description: "Resource Not Found"
          schema:
            $ref: "#/definitions/ErrorMessage"
        default:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ErrorMessage"
  /images/{id}/thumbnail:
    parameters:
    - name: "id"
      in: "path"
      description: "id of an image"
      required: true
      type: "string"
    get:
      summary: "Download a thumbnail of an image"
      description: "Download a thumbnail of an image by id"
      x-escapin-handler: "instance.imagesIdThumbnailGET"
      produces:
      - "image/jpeg"
      responses:
        200:
          description: "a thumbnail of an image"
        404:
          description: "Resource Not Found"
          schema:
            $ref: "#/definitions/ErrorMessage"
        default:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ErrorMessage"

definitions:
  Id:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
    example:
      id: "1234"
  Message:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
    example:
      message: "メッセージ"
  ErrorMessage:
    type: "object"
    required:
    - "error_code"
    - "message"
    properties:
      error_code:
        type: "string"
      message:
        type: "string"
    example:
      error_code: "エラーコード"
      message: "エラーの説明"
  List:
    type: "array"
    items:
      $ref: "#/definitions/Id"
responses:
  Succeeded:
    description: "Succeeded"
    schema:
      $ref: "#/definitions/Message"
  Created:
    description: "Resource Created"
    schema:
      $ref: "#/definitions/Id"
    headers:
      Location:
        type: "string"
        format: "uri"
        description: "URI to be assigned a new resource"
  IllegalArgument:
    description: "Illegal Argument"
    schema:
      $ref: "#/definitions/ErrorMessage"
  NotFound:
    description: "Resource Not Found"
    schema:
      $ref: "#/definitions/ErrorMessage"
  ServerError:
    description: "Server Error"
    schema:
      $ref: "#/definitions/ErrorMessage"
